version: "3.9"
services:
    proxy_server:
        image: jwilder/nginx-proxy:latest
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - /var/run/docker.sock:/tmp/docker.sock:ro
        container_name: proxy_server
        depends_on:
            - client
            - api
    api:
        image: board_api:latest
        ports:
            - 8080:8080
        container_name: api_server
    client:
        image: board_client:latest
        ports:
            - 8081:8081
        container_name: client_server
